### ISSUE TITLE
Handle Subtitles in HTML

### ISSUE THREAD

**Issue by jaruba** [bakaru/bakaru#2]
- fetch best subtitle result for each language from Open Subtitles:
https://github.com/vankasteelj/opensubtitles-api

- detect encoding (or ask your users to select it):
https://www.npmjs.com/package/charset-detector

- example usage for encoding detection and converting to utf8:
https://github.com/Ivshti/node-subtitles-grouping/blob/master/lib/retriever.js#L56-L59

- parse srt, sub, vtt subtitles:
https://github.com/jaruba/PowderPlayer/blob/react-powder/src/components/Player/workers/subtitles/parse.js

- convert ass, ssa and txt subtitles to srt so they can also be parsed:
https://github.com/oaprograms/lingo-player/issues/1

- get srt from zip, tar.gz archives:
https://github.com/Ivshti/node-subtitles-grouping/blob/master/lib/retriever.js#L17-L64

This is pretty much all I know about subtitles.. :pizza:

**Comment by RiderSx** [comment]
For ASS/SSA subs: https://github.com/Arnavion/libjass

**Comment by jaruba** [comment]
Wow, that's a great find

**Comment by RiderSx** [comment]
Wut, i didn't mean that, ugh :(
